modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="randomworldgen"
version="${file.jarVersion}"
displayName="RandomWorldGen"
description='''

'''
[[dependencies.randomworldgen]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.randomworldgen]]
    modId="minecraft"
    mandatory=true
    versionRange="1.16.5"
    ordering="NONE"
    side="BOTH"
